add fatal error fallback, fix async state errors, overlay page error
dvci/shc-web-verifier pull request #29
Opened 2022-03-09 22:31 UTC by nkarip

2022-03-10 18:33 UTC, sarahmcdougall reviewed
I tested this branch with a SHC that does not have an issuer. On our main branch, the non-issuer SHC has the “issuer not recognized” banner at the top of the screen and “issuer not recognized” text on the card itself, but on this branch the banner says that the issuer is recognized. The `issuerVerified` field is now a Promise whose PromiseState is “fulfilled” and whose PromiseResult is false, and so I believe `issuerVerified` is becoming truthy from being set with the new async `verifyIssuer()` function.

2022-03-15 14:28 UTC, mickohanlon23 requested changes
Noticed the same error as Sarah pointed out, where `issuerVerified` is always true. Other than that, the ErrorBoundary properly catches the fatal corrupted QR Code error that had previously caused the QR Scanner camera to stop working. Good addition of catch-all error handling.

2022-03-16 21:41 UTC, nkarip commented
Good catch. Updated async calls and tested with a card that does not have a recognized issuer.

2022-03-16 22:03 UTC, mickohanlon23 approved these changes

2022-03-17 19:10 UTC, sarahmcdougall approved these changes

2022-03-17 19:28 UTC, merged