DVCI-195: Reinstate Privacy Policy
dvci/shc-web-verifier pull request #72
Opened 2022-06-26 22:16 UTC by mickohanlon23

This PR adds the privacy policy back to our application:

- Add `/privacy` route and "Privacy" button in footer.
- Edits were made to the privacy policy language in accordance with our completed Privacy Review.
- Language about Google Analytics tracking was replaced with language regarding Clicky tracking to align with https://github.com/dvci/shc-web-verifier/pull/71.

2022-06-27 14:45 UTC, sarahmcdougall requested changes

2022-06-29 14:50 UTC, mickohanlon23 commented on public/locales/en/translation.json
> +        "content": "We use Clicky, a third-party web analytics service, to help us understand and analyze how the Verifier web application is used. This service is configured so that it does not use
What about:

> "We use Clicky, a third-party web analytics service, to help track the number of visitors to the Verifier web application in a privacy-preserving way."

2022-06-29 14:51 UTC, mickohanlon23 commented on public/locales/en/translation.json
> +        "content": "We use Clicky, a third-party web analytics service, to help us understand and analyze how the Verifier web application is used. This service is configured so that it does not use
Updated: https://github.com/dvci/shc-web-verifier/pull/72/commits/ddefd695556e3f75910cc1db41c3dc81a7d18e42

2022-06-29 16:15 UTC, sarahmcdougall commented on public/locales/en/translation.json
> +        "content": "We use Clicky, a third-party web analytics service, to help us understand and analyze how the Verifier web application is used. This service is configured so that it does not use
I think that sounds good!

2022-06-29 16:41 UTC, mickohanlon23 commented on public/locales/en/translation.json
> +        "content": "We use Clicky, a third-party web analytics service, to help us understand and analyze how the Verifier web application is used. This service is configured so that it does not use
Great, I made the update here: https://github.com/dvci/shc-web-verifier/pull/72/commits/c4a277b21502007ddd932c4f35aefd31bf691658

2022-06-29 16:46 UTC, mickohanlon23 commented on public/locales/en/translation.json
> +        "content": "We use Clicky, a third-party web analytics service, to help us understand and analyze how the Verifier web application is used. This service is configured so that it does not use
> I like the inclusion of the link to opt out of Clicky. Should we try testing this by having someone log into our Clicky page and have someone else opt out of Clicky and then open the web verifier to check that their visit doesn't get tracked?

@sarahmcdougall confirmed that the Opt-out feature works, so I'll resolve this thread, but feel free to re-open if there are issues.

2022-06-29 16:53 UTC, sarahmcdougall approved these changes
I think this needs a rebase since we updated the `translation.json`, but otherwise everything seems to be working! Thanks for handling the privacy policy changes!

2022-06-29 17:15 UTC, mickohanlon23 commented
I am going to double-check the final privacy policy updates we made with the Privacy team that led our review, but once that is complete I will plan to merge this.

2022-07-01 17:14 UTC, mickohanlon23 commented
I made updates based upon the final Privacy Policy edits Linda sent on 6/30. @sarahmcdougall would you mind taking a final look before I merge?

2022-07-03 13:01 UTC, sarahmcdougall commented
> I made updates based upon the final Privacy Policy edits Linda sent on 6/30. @sarahmcdougall would you mind taking a final look before I merge?

Just read through it and it sounds good to me!

2022-07-06 13:16 UTC, merged