update CDSi supporting data to v4.31, primary series names and unit t…
dvci/shc-web-verifier pull request #76
Opened 2022-07-13 20:46 UTC by nkarip

…ests

2022-07-15 15:59 UTC, karbates approved these changes
I reviewed the changes and do not see any issues

2022-07-18 18:19 UTC, sarahmcdougall requested changes

2022-07-18 18:19 UTC, sarahmcdougall commented on src/components/Validator/Validator.test.js
> +  const patientBundle = createPatientBundle(new Date(2020, 4, 30), [
```suggestion
  const patientBundle = createPatientBundle(new Date(2010, 4, 30), [
```

2022-07-18 18:19 UTC, sarahmcdougall commented on src/components/Validator/Validator.test.js
> +    { dateAdministered: '2022-06-27', cvx: '218' }
```suggestion
    { dateAdministered: '2022-06-27', cvx: '228' }
```

2022-07-18 18:19 UTC, sarahmcdougall commented on src/components/Validator/Validator.test.js
> +    { dateAdministered: '2022-06-25', cvx: '218' }
```suggestion
    { dateAdministered: '2022-05-28', cvx: '228' },
    { dateAdministered: '2022-06-25', cvx: '228' }
```

2022-07-18 18:19 UTC, sarahmcdougall commented on src/components/Validator/Validator.test.js
> +  const patientBundle = createPatientBundle(new Date(2020, 5, 30), [
```suggestion
  const patientBundle = createPatientBundle(new Date(2020, 4, 30), [
```

2022-07-20 12:52 UTC, sarahmcdougall approved these changes

2022-07-20 12:53 UTC, merged